### ISSUE TITLE
Adicionar Sistema de votação para respostas

### ISSUE THREAD

**Issue by wfaq** [wfaq/wfaq-backend#6]

**Comment by wfaq** [comment]
Voto Positivo - Verificar se usuario já votou positivo se sim não adiciona novo voto e retorna mensagem se não votou adiciona voto.
Voto negativo -  mesmas verificações do positivo
Pode alterar voto de positivo para negativo
Pode retirar voto
Serão 2 arrays dentro do objeto resposta

**Comment by benitezdouglas** [comment]
Finalizado!
